management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: "true"
    health:
      show-details: "always"




#  main:
#    allow-bean-definition-overriding: true
spring:
  jpa:
    hibernate:
      ddl-auto: update  # Or "validate", "create", "create-drop"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/shopx2
    driver-class-name: org.postgresql.Driver